package com.dao;

import java.util.List;

import com.entity.Message;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    int deleteByPrimaryKey(Integer id);
    
    List<Message> getAllmessageList();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbggenerated Thu Sep 06 14:33:19 CST 2018
     */
    int updateByPrimaryKey(Message record);
}